### ISSUE TITLE
Function footprint of displayPublishPanel is missing the entry ID

### ISSUE THREAD

**Issue by michael-e** [symphonists/system_date_fields#10]
Currently we have:

```php
public function displayPublishPanel(&$wrapper, $data = null, $error = null, $prefix = null, $postfix = null)
```

But it should be:

```php
public function displayPublishPanel(XMLElement &$wrapper, $data = null, $flagWithError = null, $fieldnamePrefix = null, $fieldnamePostfix = null, $entry_id = null)
```

So:

* it's missing the entry ID currently
* parameter names should ideally be the same as in Symphony's `lib/toolkit/class.field.php` 

The proposed change would also fix #9.

**Comment by nitriques** [comment]
This is some pretty old code https://github.com/symphonists/system_date_fields/commit/d9663571801b7c7d9222576e718706f4e96d478f almost 4 years ago! 

BTW both fields have this problem. I can't believe I've ship this so many times and nobody complained.

**Comment by nitriques** [comment]
I like the 'footprint' idea! :) It's actually the method's signature :P

**Comment by michael-e** [comment]
:-)

**Comment by nitriques** [comment]
Sorry I had to rebase ... But it's fixed now!
