### ISSUE TITLE
Don't use PHP's strtotime function

### ISSUE THREAD

**Issue by michael-e** [symphonists/system_date_fields#12]
The fields use `strtotime`, but Symphony has its own datetime object/functions. Symphony's `DateTime` object can do the work, e.g. instead of:

```php
$value = DateTimeObj::get(__SYM_DATE_FORMAT__, strtotime($row['creation_date_gmt'] . ' +00:00'));
```

we can simply use:

```php
$value = DateTimeObj::get(__SYM_DATE_FORMAT__, $row['creation_date_gmt'] . ' +00:00');
```

**Comment by nitriques** [comment]
+1000. #5 and #6 would benefit from using more core things.
