### ISSUE TITLE
Evaluate the usage of GMT dates

### ISSUE THREAD

**Issue by michael-e** [symphonists/system_date_fields#13]
Both fields use GMT values from the database.

Symphony saves two values to the entry table: The GMT value ond the localized value. Somtimes both values are retrieved, but sometimes only one of them – the localized one — is retrieved, e.g. when outputting XML to the frontend in `class.datasource.section.php`.

It should be evaluated:

* If Symphony does this right — is saving localized plus GMT values the best way to deal with these system dates?
* When the first question is answered: Should/must it be done differently in this extension?

**Comment by nitriques** [comment]
Only GMT should be used. We do not care about what timezone it has been created in.

Since this field is only a way to get system date in the UI, I think it's safe to change.

**Comment by michael-e** [comment]
Currently the fields in this extension do it right (GMT). Symphony does it wrong (using the localized date, and assuming that this has been saved with the current timezone setting). Imagine ever changing the timezone of your installation, in this case all system dates would be wrong.

Should we post this a s a Symphony issue?

**Comment by nitriques** [comment]
> Should we post this a s a Symphony issue?

Yes. 

> Currently the fields in this extension do it right (GMT). Symphony does it wrong

But this is what is bugging me. This fields **do not** store any value (they used the core one) see https://github.com/symphonists/system_date_fields/blob/master/fields/field.systemcreateddate.php#L67-L74 So Symphony is right and wrong at the same time ?

I would not mind saving the original date with the timestamp, but never use it.

**Comment by nitriques** [comment]
> but never use it.

Meaning that extension developers could use it, but the core would only use GTM time

**Comment by michael-e** [comment]
If you look at the database table, you will see what I mean. Symphony **saves two values** (localized and GMT, both without time offset). The extension here **reads** the **GMT** value (and outputs it as localized date), which is fine. But Symphony **reads** from the **localized** column and assumes that it has been saved with the time offset given in the config file. There are several flaws here:

* saving the same timestamp in two different representations (GMT and localized) is useless and  increases the probability of error
* reading a localized date and assuming a time offset is error-prone as well (see my example above, changing the time zone)

**Comment by nitriques** [comment]
Yeah we understand the same thing

> saving the same timestamp in two different representations (GMT and localized) is useless and increases the probability of error

This is where I do not agree. I like to have both. Would saving the GMT time + "original" timezone offset work with you (so we do not duplicate data?) I like to know in which timezone the record has been created/updated.

> reading a localized date and assuming a time offset is error-prone as well 

If you do not convert it, there are not problem. Should the core use that ? no, never. But extension developers could display/use the "original" timezone offset to display it.

**Comment by michael-e** [comment]
Sorry, I don't get your point. The timezone will always be the timezone from the config file. What dou you mean when you say *"original" timezone offset*? Some sort of "historical information" (i.e. Symphony's timezone setting when the entry was created/updated)?

Remember, we are talking about **system dates**!

**Comment by nitriques** [comment]
> The timezone will always be the timezone from the config file.

Right now yes, you are right. I am more talking about what it *should* be (in the future)

>  Some sort of "historical information"

Yes!

> Remember, we are talking about system dates!

I know! But I am not talking about what we do right now in the core (which is wrong) :) Maybe not the ideal place to discuss this, I agree.

**Comment by michael-e** [comment]
We should open a new Symphony issue called "evaluate system date logic" or similar.

We both agree that the extension does it right (using the GMT value), so I am closing this issue.

**Comment by nitriques** [comment]
Perfect. https://github.com/symphonycms/symphony-2/issues/2517
