### ISSUE TITLE
Fields seem to ignore timezone-setting before saving an entry (1.1)

### ISSUE THREAD

**Issue by twiro** [symphonists/system_date_fields#16]
As the title says - when creating a new entry the shown time seems to be in GMT - ignoring my timezone setting:

![system-date-field-new-saved-timezone-bug](https://cloud.githubusercontent.com/assets/870227/11681042/aaad4954-9e5c-11e5-8669-d4443097fadf.png)

**Comment by nitriques** [comment]
Hum... Which timezone are you in ? +1 ?

**Comment by twiro** [comment]
> _Hum... Which timezone are you in ? +1 ?_

Exactly - Germany = GMT+1

**Comment by nitriques** [comment]
And the server is in the same timezone too ?

Remember the date is formatted server side. Thinking about that we, should use gtm time in timeago, not the actual user's time.

**Comment by nitriques** [comment]
> Thinking about that we, should use gtm time in timeago, not the actual user's time.

It does uses UTC :)

**Comment by nitriques** [comment]
This might be of interest: http://stackoverflow.com/questions/17694894/different-timezone-types-on-datetime-object
