### ISSUE TITLE
Throws errors in logfile

### ISSUE THREAD

**Issue by animaux** [symphonists/system_date_fields#20]
On Symphony `10.7.beta2` the current `system_date_fields` throws an error when trying to save an entry:

    26. April 2017 12:22 > UNKNOWN: DatabaseException 0 - MySQL-Fehler (1146): Table '….sym_entries_data_74' doesn't exist in Abfrage: LOCK TABLES sym_entries_data_74 WRITE on line 961 of /homepages/5/d18796433/htdocs/2017/symphony/lib/toolkit/class.mysql.php

This is likely since the field does not actually store any data but only reveals data stored elsewhere. So the table symphony tries to lock is not existant.

**Comment by nitriques** [comment]
Will be fixed in the core. Thanks!
