### ISSUE TITLE
Sorting DS after system_date_fields renders mySQL error 

### ISSUE THREAD

**Issue by animaux** [symphonists/system_date_fields#22]
Symphony 2.7.4
PHP 7.0.29-1

		<error><![CDATA[MySQL-Fehler (3065): Expression #1 of ORDER BY clause is not in SELECT list, references column 'db-10038-1.e.creation_date_gmt' which is not in SELECT list; this is incompatible with DISTINCT in Abfrage: SELECT SQL_CACHE DISTINCT `e`.`id`, `e`.section_id,
		`e`.`author_id`, `e`.`modification_author_id`,
		`e`.`creation_date` AS `creation_date`,
		`e`.`modification_date` AS `modification_date`

		FROM `sym_entries` AS `e`

		LEFT JOIN
		`sym_entries_data_161` AS t161_1
		ON (e.id = t161_1.entry_id)
		LEFT JOIN `sym_entries_data_162` AS `t162_0` ON (`e`.`id` = `t162_0`.entry_id) 
		WHERE 1

		AND `e`.`section_id` = 15

		AND (
				t161_1.value IN ('yes')
				OR
				t161_1.value IS null
		)
		AND (
										t162_0.value IN ('formulare-buchhaltung')
										OR t162_0.handle IN ('formulare-buchhaltung')
								) 
		ORDER BY `e`.`creation_date_gmt` DESC on 964 of file /…/symphony/lib/toolkit/class.mysql.php]]></error>

**Comment by nitriques** [comment]
This is not related to PHP but rather MySQL 5.7.

Can you change the order to use `creation_date` and `modification_date` (remove the `_gmt` part)

**Comment by animaux** [comment]
I presume in the `field.*.php` files? I tried with the same result. 

For some reason an unfiltered view of the entries work. The error only shows up as soon as there is filtering on another field in the section going on.

**Comment by animaux** [comment]
`ORDER BY `e`.`creation_date_gmt` DESC on 964 of file /…/symphony/lib/toolkit/class.mysql.php]]></error>` Do I need to remove the gmt part in the core too?

**Comment by animaux** [comment]
This part of the error stays the same even if I remove the `_gmt`-part in the field php:

   ORDER BY `e`.`creation_date_gmt` DESC on 964 of file /…/symphony/lib/toolkit/class.mysql.php]]></error>

Is this cached somewhere?

**Comment by nitriques** [comment]
@animaux 2 places

https://github.com/symphonists/system_date_fields/blob/master/fields/field.systemcreateddate.php#L18
https://github.com/symphonists/system_date_fields/blob/master/fields/field.systemmodifieddate.php#L18

**Comment by animaux** [comment]
~~I removed both `_gmt`s but still get the error when trying to use the field for sorting.~~

~~Sorry. Had a look again. It does work now. Not sure if I did something else.~~

D’oh, sorry, not my day today. It does work in one section, but not in another. Have to figure out why.

**Comment by animaux** [comment]
Looking at it again, this doesn’t seem to be a problem with this extension, but rather the system_date by symphony itself. I’m still puzzled as to why it works fine with one section and not the other.

**Comment by animaux** [comment]
It works if I actually add a field from the extension to the section and sort after this, rather than the sort option provided by the system.

I’m closing this, because it seems to be a very specific issue that’s not really reproducable.
