### ISSUE TITLE
On the publish page, dates always are the current date

### ISSUE THREAD

**Issue by michael-e** [symphonists/system_date_fields#9]
On the publish page, the extension does not display the saved datetime values, but the current datetime. This caused by a wrong function footprint.

**Comment by michael-e** [comment]
See #10.

**Comment by nitriques** [comment]
damn. thanks.

**Comment by michael-e** [comment]
This should have been fixed by 2947b453e53dbf3634e91d19076cb7ab58bc53c7 (the fix for #10).

**Comment by nitriques** [comment]
I confirm!
